# Действия с предложениями

## Получить все предложения

GET http://localhost:3000/offers?city=Paris HTTP/1.1
Content-Type: application/json

###

## Получить премиальные предложения

GET http://localhost:3000/offers/premium?city=Paris HTTP/1.1
Content-Type: application/json

###

## Получить предложение по id

GET http://localhost:3000/offers/65003da828e9139d34479c8b HTTP/1.1
Content-Type: application/json

###

## Обновить предложение по id

PATCH http://localhost:3000/offers/6500550d2aa0e0f2ddb409ec HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiY2FAa2UuY24iLCJpZCI6IjY1MDA1NDk1YTkzMjBhZmZkOGQxMDdiYiJ9LCJpYXQiOjE2OTQ1MjA1NTUsImV4cCI6MTY5NTEyNTM1NX0.bkRvzRbJEDG9f3qcNYfGJmVSvhud_md4aDQeSmCbC2o

{
  "title": "Новое заголовок предложения"
}

###

## Удалить предложение по id

DELETE  http://localhost:3000/offers/64f5dd45cd1bc981b87cab80 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiYWVhQGtlLmNuIiwiaWQiOiI2NGZmMzAxMTk2NTAxODkzMmRhMzI0YzgifSwiaWF0IjoxNjk0NDQ1NjQwLCJleHAiOjE2OTUwNTA0NDB9.3iv5pwHjEtCIAkWmWTayhcHEgmcFSZ09b0WYUZIWZag

###

## Создать предложение

POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiY2FAa2UuY24iLCJpZCI6IjY1MDA1NDk1YTkzMjBhZmZkOGQxMDdiYiJ9LCJpYXQiOjE2OTQ1MjA1NTUsImV4cCI6MTY5NTEyNTM1NX0.bkRvzRbJEDG9f3qcNYfGJmVSvhud_md4aDQeSmCbC2o

{
  "title": "2-к. квартира, 55 м²",
  "description": "Новый, одно подъездный дом, обеспечен пассажирским и грузопассажирским лифтами с выходом в подземный паркинг.",
  "date": "Fri Sep 01 2023 16:40:43 GMT+0300 (Москва, стандартное время)",
  "city": {
    "name": "Paris",
    "coordinates": {
      "latitude": 48.85661,
      "longitude": 2.351499
    }
  },
  "preview": "http://pawof.bb/fa3.jpg",
  "pictures": [
      "http://pawof.bb/fa.jpg",
      "http://pawof.bb/fa2.jpg",
      "http://pawof.bb/fa3.jpg",
      "http://pawof.bb/fa4.jpg",
      "http://pawof.bb/fa5.jpg",
      "http://pawof.bb/fa6.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "raiting": 2.2,
  "houseType": "room",
  "rooms": 3,
  "guests": 2,
  "price": 10497,
  "equipment": [
      "Baby seat",
      "Washer",
      "Towels",
      "Fridge"
  ],
  "commentsCount": 32,
  "coordinates": {
      "latitude": 50.938361,
      "longitude": 6.959974
  }
}
###
