export enum AppComponent {
  RestApplication = 'RestApplication',
  LoggerInterface = 'LoggerInterface',
  ConfigInterface = 'ConfigInterface',
  DatabaseClientInterface = 'DatabaseClientInterface',
  UserServiceInterface = 'UserServiceInterface',
  UserModel = 'UserModel',
  UserController = 'UserController',
  OfferServiceInterface = 'OfferServiceInterface',
  OfferModel = 'OfferModel',
  OfferController = 'OfferController',
  CommentServiceInterface = 'CommentServiceInterface',
  CommentModel = 'CommentModal',
  CommentController = 'CommentController',
  CityServiceInterface = 'CityServiceInterface',
  CityModel = 'CityModel',
  FavoriteServiceInterface = 'FavoriteServiceInterface',
  FavoriteModel = 'FavoriteModel',
  FavoriteController = 'FavoriteController',
  BaseExceptionFilter = 'BaseExceptionFilter',
  ValidationExceptionFilter = 'ValidationExceptionFilter',
  HttpErrorExceptionFilter = 'HttpErrorExceptionFilter',
}
