export enum AppComponent {
  RestApplication = 'RestApplication',
  LoggerInterface = 'LoggerInterface',
  ConfigInterface = 'ConfigInterface',
  DatabaseClientInterface = 'DatabaseClientInterface',
  UserServiceInterface = 'UserServiceInterface',
  UserModel = 'UserModel',
  OfferServiceInterface = 'OfferServiceInterface',
  OfferModel = 'OfferModel',
  CommentServiceInterface = 'CommentServiceInterface',
  CommentModel = 'CommentModal',
  CityServiceInterface = 'CityServiceInterface',
  CityModel = 'CityModel',
  FavoriteServiceInterface = 'FavoriteServiceInterface',
  FavoriteModel = 'FavoriteModel',
}
