# Действия с комментариями
## Создание комментария

POST http://localhost:3000/comments/651d629106b516166d592487 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1MDg1YjU3Y2U5ZjJhMzE2MjY3MzAzZiIsImlhdCI6MTY5NjQwNjk0MywiZXhwIjoxNjk3MDExNzQzfQ.ODsgWperPWwEmrpOEbMQfbGX48IXrGp21mTW-NLUXkY

{
  "comment": "Новый комментарий 2",
  "rating": 4
}

###

## Получить все комментарии к предложению

GET http://localhost:3000/comments/651d629106b516166d592487 HTTP/1.1
Content-Type: application/json

###
