# Действия с комментариями
## Создание комментария

POST http://localhost:5000/comments/652cf61fdb625c5df1b3b8db HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1MmQwMmI2NjVlNDFjYzY1NWVmYzRhMSIsImlhdCI6MTY5NzYxMDM2MywiZXhwIjoxNjk4MjE1MTYzfQ.69Q9FN75fU16IKIY3vkvriFOOd5OEGEj1wFWXA6rEbs

{
  "comment": "Новый комментарий 2",
  "rating": 4
}

###

## Получить все комментарии к предложению

GET http://localhost:5000/comments/652cf61fdb625c5df1b3b8db HTTP/1.1
Content-Type: application/json

###
